server:
  port: 8084

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${ts.nacos.host}:${ts.nacos.port}

feign:
  okhttp:
    enabled: true

ts:
  swagger:
    title: "云商城交易管理接口文档"
    package: com.tscloud.trade.controller
