server:
  port: 8086

seata:
  tx-service-group: tscloud
  service:
    vgroup-mapping:
      tscloud: "default"
    grouplist:
      default: localhost:8091

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${ts.nacos.host}:${ts.nacos.port}

ts:
  es:
    uri: http://localhost:19200
  swagger:
    title: "云商城搜索管理接口文档"
    package: com.tscloud.search.controller
