server:
  port: 8083

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${ts.nacos.host}:${ts.nacos.port}

feign:
  okhttp:
    enabled: true

ts:
  jwt:
    location: classpath:tscloud.jks
    alias: tscloud
    password: tscloud123
    tokenTTL: 30m
  swagger:
    title: "云商城用户管理接口文档"
    package: com.tscloud.user.controller
