server:
  port: 8083

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${hm.nacos.host}:${hm.nacos.port}

feign:
  okhttp:
    enabled: true

hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  swagger:
    title: "黑马商城用户管理接口文档"
    package: com.hmall.user.controller
