server:
  port: 8082
  tomcat:
    threads:
      max: 50 # 允许的最大线程数
    accept-count: 50 # 最大排队等待数量
    max-connections: 100 # 允许的最大连接

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${ts.nacos.host}:${ts.nacos.port}

seata:
  tx-service-group: tscloud
  service:
    vgroup-mapping:
      tscloud: "default"
    grouplist:
      default: localhost:8091

feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true # 开启feign对sentinel的支持

ts:
  cart:
    max-items: 10
  db:
    host: ${ts.db.host}
    port: ${ts.db.port}
    pw: ${ts.db.pw}
    database: ${ts.db.database}
  swagger:
    title: "云商城购物车服务接口文档"
    package: com.tscloud.cart.controller
