server:
  port: 8080
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${hm.nacos.host}:${hm.nacos.port}
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /users/admin/login
      - /items/**
      - /hi
    adminPaths:
      - /orders/page
      - /upload/**