server:
  port: 8081

seata:
  tx-service-group: tscloud
  service:
    vgroup-mapping:
      tscloud: "default"
    grouplist:
      default: localhost:8091

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${ts.nacos.host}:${ts.nacos.port}
  redis:
    host: localhost
    port: 6379

ts:
  swagger:
    title: "云商城商品管理接口文档"
    package: com.tscloud.item.controller
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: ${TS_OSS_ACCESS_KEY_ID:}
    accessKeySecret: ${TS_OSS_ACCESS_KEY_SECRET:}
    bucketName: ${TS_OSS_BUCKET:}
